//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliosoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallePrestamo
    {
        public int idDetalle { get; set; }
        public Nullable<int> idPrestamo { get; set; }
        public Nullable<int> idLibro { get; set; }
    
        public virtual libross libross { get; set; }
        public virtual prestamos prestamos { get; set; }
    }
}
