//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliosoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int idEmpleado { get; set; }
        public int tipoEmpleado { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string apeYnombre { get; set; }
        public int dni { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
    }
}
