//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliosoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class libross
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public libross()
        {
            this.detallePrestamo = new HashSet<detallePrestamo>();
        }
    
        public int idLibro { get; set; }
        public string titulo { get; set; }
        public Nullable<int> año { get; set; }
        public string editorial { get; set; }
        public int idProveedor { get; set; }
        public int idAutor { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual proveedores proveedores { get; set; }
        public virtual autores autores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallePrestamo> detallePrestamo { get; set; }
    }
}
