//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliosoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaSocios
    {
        public int idSocio { get; set; }
        public string tipoDeSocio { get; set; }
        public int DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string Dirección { get; set; }
        public string Telefono { get; set; }
    }
}
