//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliosoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaEmpleados
    {
        public int ID_del_Empleado { get; set; }
        public string Tipo_de_Empleado { get; set; }
        public int DNI { get; set; }
        public string Apellido_y_nombre { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_de_nacimiento { get; set; }
        public string Dirección { get; set; }
        public string Telefono { get; set; }
    }
}
