//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliosoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaLibros
    {
        public int ID_del_libro { get; set; }
        public string Título { get; set; }
        public Nullable<int> Año { get; set; }
        public string Editorial { get; set; }
        public string Autor { get; set; }
        public string Proveedor { get; set; }
        public string Prestado { get; set; }
    }
}
